services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "7777:7777"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://root:cutestar12@db:3306/OOTC
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy && node dist/main.js"

  db:
    image: mysql:8.0
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cutestar12
      MYSQL_DATABASE: OOTC
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/config:/etc/mysql/conf.d
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -pcutestar12" ]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db_data:
