version: "3.9"  # Optional version number
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development  # Optional: Specify target stage to build
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cutestar12
      MYSQL_DATABASE: OOTC
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/config:/etc/mysql/conf.d
      - ./db/mysql/init:/docker-entrypoint-initdb.d
